// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package runner

import (
	"context"
	"sync"
)

// Ensure, that GitHubMock does implement GitHub.
// If this is not the case, regenerate this file with moq.
var _ GitHub = &GitHubMock{}

// GitHubMock is a mock implementation of GitHub.
//
//	func TestSomethingThatUsesGitHub(t *testing.T) {
//
//		// make and configure a mocked GitHub
//		mockedGitHub := &GitHubMock{
//			OpenBumpPRFunc: func(ctx context.Context, in BumpPRInput) (int, error) {
//				panic("mock out the OpenBumpPR method")
//			},
//			ReadFileFunc: func(ctx context.Context, path string, ref string) ([]byte, string, error) {
//				panic("mock out the ReadFile method")
//			},
//		}
//
//		// use mockedGitHub in code that requires GitHub
//		// and then make assertions.
//
//	}
type GitHubMock struct {
	// OpenBumpPRFunc mocks the OpenBumpPR method.
	OpenBumpPRFunc func(ctx context.Context, in BumpPRInput) (int, error)

	// ReadFileFunc mocks the ReadFile method.
	ReadFileFunc func(ctx context.Context, path string, ref string) ([]byte, string, error)

	// calls tracks calls to the methods.
	calls struct {
		// OpenBumpPR holds details about calls to the OpenBumpPR method.
		OpenBumpPR []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In BumpPRInput
		}
		// ReadFile holds details about calls to the ReadFile method.
		ReadFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
			// Ref is the ref argument value.
			Ref string
		}
	}
	lockOpenBumpPR sync.RWMutex
	lockReadFile   sync.RWMutex
}

// OpenBumpPR calls OpenBumpPRFunc.
func (mock *GitHubMock) OpenBumpPR(ctx context.Context, in BumpPRInput) (int, error) {
	if mock.OpenBumpPRFunc == nil {
		panic("GitHubMock.OpenBumpPRFunc: method is nil but GitHub.OpenBumpPR was just called")
	}
	callInfo := struct {
		Ctx context.Context
		In  BumpPRInput
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockOpenBumpPR.Lock()
	mock.calls.OpenBumpPR = append(mock.calls.OpenBumpPR, callInfo)
	mock.lockOpenBumpPR.Unlock()
	return mock.OpenBumpPRFunc(ctx, in)
}

// OpenBumpPRCalls gets all the calls that were made to OpenBumpPR.
// Check the length with:
//
//	len(mockedGitHub.OpenBumpPRCalls())
func (mock *GitHubMock) OpenBumpPRCalls() []struct {
	Ctx context.Context
	In  BumpPRInput
} {
	var calls []struct {
		Ctx context.Context
		In  BumpPRInput
	}
	mock.lockOpenBumpPR.RLock()
	calls = mock.calls.OpenBumpPR
	mock.lockOpenBumpPR.RUnlock()
	return calls
}

// ReadFile calls ReadFileFunc.
func (mock *GitHubMock) ReadFile(ctx context.Context, path string, ref string) ([]byte, string, error) {
	if mock.ReadFileFunc == nil {
		panic("GitHubMock.ReadFileFunc: method is nil but GitHub.ReadFile was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
		Ref  string
	}{
		Ctx:  ctx,
		Path: path,
		Ref:  ref,
	}
	mock.lockReadFile.Lock()
	mock.calls.ReadFile = append(mock.calls.ReadFile, callInfo)
	mock.lockReadFile.Unlock()
	return mock.ReadFileFunc(ctx, path, ref)
}

// ReadFileCalls gets all the calls that were made to ReadFile.
// Check the length with:
//
//	len(mockedGitHub.ReadFileCalls())
func (mock *GitHubMock) ReadFileCalls() []struct {
	Ctx  context.Context
	Path string
	Ref  string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
		Ref  string
	}
	mock.lockReadFile.RLock()
	calls = mock.calls.ReadFile
	mock.lockReadFile.RUnlock()
	return calls
}
