name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v7

      - uses: jdx/mise-action@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: golangci-lint
        run: golangci-lint run

      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-check
          fail_level: error
          filter_mode: nofilter

      - uses: reviewdog/action-yamllint@v1
        with:
          reporter: github-check
          fail_level: error
          filter_mode: nofilter
          yamllint_flags: "-c .yamllint.yml ."
