name: mise-bump-example

on:
  workflow_dispatch: {}

jobs:
  mise-bump-example:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - uses: sgash708/mise-bump-action@v0.2.1
        with:
          mise-config-path: examples/single-tool/mise.toml
          pr-strategy: per-tool
